# Development configuration overrides
# This file is merged with _config.yml when running in dev mode
# Usage: bundle exec jekyll serve --config _config.yml,_config_dev.yml

url: ''
baseurl: ''
dev_mode: 1
